### ISSUE TITLE
How to install MtApi.ex4

### ISSUE THREAD

**Issue by laptio** [EAScript/EAMT#1]
Hi !
How to install MtApi.ex4 into metatrader ?
I tried to put file into Experts folder .
When I start metatrader - the file is delete.
Maybe I do smth wrong ?

**Comment by EAScript** [comment]
Hello
Yes, there is a problem and I have to replace the correct installation file.
To solve this issue, you can download the MtApi.ex4 file from the original MtApi project.
I taught this in an Instagram post. You can use it for installation to solve this problem.
https://www.instagram.com/p/CMdx4DGghsF/
